# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy the contents of the frontend folder to the default Nginx public directory
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80