version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: lucaspascal/flask_app:1.0.0
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    container_name: html_app
    image: lucaspascal/html_app:1.0.0
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - flask_app
volumes:
  pgdata: {}