version: '3.8'

services:
  # PostgreSQL service
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # Mapping PostgreSQL port

  # Python application service
  app:
    build:
      context: ./backend  
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db  # PostgreSQL host
      DB_NAME: finance
      DB_USER: finance
      DB_PASSWORD: finance
    ports:
      - "5000:5000" 
